// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDr5llB0JIWXYE-2VIsjEuX2mrQD6T0p0',
    appId: '1:389306761187:web:04056ba43419fc8ca7aad6',
    messagingSenderId: '389306761187',
    projectId: 'rebuy-675c7',
    authDomain: 'rebuy-675c7.firebaseapp.com',
    storageBucket: 'rebuy-675c7.appspot.com',
    measurementId: 'G-EJFEN9MB3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMyTZJAlwf38FC06_g-CVmpAh_Fq9zPRc',
    appId: '1:389306761187:android:cf376c34a89bc699a7aad6',
    messagingSenderId: '389306761187',
    projectId: 'rebuy-675c7',
    storageBucket: 'rebuy-675c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRSrNz3OLMWjAcZJp_NlJTi-nE_9wbjRw',
    appId: '1:389306761187:ios:12b9eb007f9ce9eda7aad6',
    messagingSenderId: '389306761187',
    projectId: 'rebuy-675c7',
    storageBucket: 'rebuy-675c7.appspot.com',
    iosBundleId: 'com.rebuy.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRSrNz3OLMWjAcZJp_NlJTi-nE_9wbjRw',
    appId: '1:389306761187:ios:e407a914fbdbe96aa7aad6',
    messagingSenderId: '389306761187',
    projectId: 'rebuy-675c7',
    storageBucket: 'rebuy-675c7.appspot.com',
    iosBundleId: 'com.example.rebuy.RunnerTests',
  );
}
